# -*- coding: utf-8 -*-
"""lime_explainer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HIA7eeWwfzSiJSUJnyt6KLLFbIkH79o
"""

from lime.lime_text import LimeTextExplainer
from model import predict_sentiment

# Initialize the LIME explainer with class names
explainer = LimeTextExplainer(class_names=['negative', 'neutral', 'positive'])

def explain_prediction(text):
    # Predict using the model
    prediction = predict_sentiment(text)
    print(f"Prediction: {prediction}")

    # Explain the prediction using LIME
    explanation = explainer.explain_instance(text, predict_fn=predict_sentiment, num_features=10)

    # Visualize the explanation
    explanation.show_in_notebook(text=True)
