# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HIA7eeWwfzSiJSUJnyt6KLLFbIkH79o
"""

from transformers import pipeline

# Load the sentiment-analysis model from Hugging Face
nlp = pipeline('sentiment-analysis')

def predict_sentiment(text):
    prediction = nlp(text)
    return prediction